# AdInsight AI

## Notebook 01 – Data Understanding

### Objective

This notebook connects to Google BigQuery, loads the Google Analytics Sample Dataset into Python, and performs the initial exploratory data analysis.

### Technologies

- Google BigQuery
- Python
- Pandas
- Matplotlib
- Plotly

### Dataset

Google Analytics Sample Dataset

Project:
adinsight-ai-504406

In [1]:
# =====================================================
# Import Libraries
# =====================================================

from google.cloud import bigquery
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
# =====================================================
# Create BigQuery Client
# =====================================================

client = bigquery.Client(
    project="adinsight-ai-504406"
)

print("Connected to BigQuery!")

Connected to BigQuery!

In [17]:
query = """
SELECT

    fullVisitorId,
    visitId,

    PARSE_DATE('%Y%m%d', date) AS visit_date,

    channelGrouping,

    trafficSource.source,
    trafficSource.medium,
    trafficSource.campaign,

    device.deviceCategory,
    device.browser,
    device.operatingSystem,

    geoNetwork.country,

    totals.pageviews,
    totals.hits,
    totals.timeOnSite,
    totals.transactions,
    totals.transactionRevenue,
    totals.newVisits,
    totals.bounces

FROM
`bigquery-public-data.google_analytics_sample.ga_sessions_*`

LIMIT 100000
"""

In [18]:
pip show db-dtypes

Name: db-dtypes
Version: 1.7.1
Summary: Pandas Data Types for SQL systems (BigQuery, Spanner)
Home-page: https://github.com/googleapis/google-cloud-python/tree/main/packages/db-dtypes
Author: The db-dtypes Authors
Author-email: googleapis-packages@google.com
License:
Location: d:\Ankita\Github projects\AdInsight-AI\.venv\Lib\site-packages
Requires: numpy, packaging, pandas, pyarrow
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [19]:
import db_dtypes

print("db-dtypes installed successfully!")

db-dtypes installed successfully!

In [20]:
# =====================================================
# Execute Query
# =====================================================

df = client.query(query).to_dataframe()

df

d:\Ankita\Github projects\AdInsight-AI\.venv\Lib\site-packages\google\cloud\bigquery\table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,fullVisitorId,visitId,visit_date,channelGrouping,source,medium,campaign,deviceCategory,browser,operatingSystem,country,pageviews,hits,timeOnSite,transactions,transactionRevenue,newVisits,bounces
0,4598890394865817235,1486932897,2017-02-12,Direct,(direct),(none),(not set),mobile,Android Webview,Android,Netherlands,1,1,<NA>,<NA>,<NA>,1,1
1,085297959192196865,1486906252,2017-02-12,Organic Search,google,organic,(not set),mobile,Chrome,Android,United Kingdom,1,1,<NA>,<NA>,<NA>,<NA>,1
2,2211677311320024670,1486956669,2017-02-12,Direct,(direct),(none),(not set),mobile,Chrome,Android,Argentina,1,1,<NA>,<NA>,<NA>,<NA>,1
3,8969779493563769417,1486922640,2017-02-12,Organic Search,google,organic,(not set),mobile,Safari,iOS,United States,1,1,<NA>,<NA>,<NA>,<NA>,1
4,9271977665405126573,1486922683,2017-02-12,Organic Search,google,organic,(not set),desktop,Safari,Macintosh,United States,1,1,<NA>,<NA>,<NA>,<NA>,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,9893771940595074714,1496376646,2017-06-01,Organic Search,google,organic,(not set),desktop,Chrome,Windows,Canada,2,2,23,<NA>,<NA>,1,<NA>
99996,0381918083080576832,1496328241,2017-06-01,Organic Search,google,organic,(not set),desktop,Firefox,Windows,Norway,2,2,15,<NA>,<NA>,1,<NA>
99997,0322360644586354491,1496344223,2017-06-01,Organic Search,google,organic,(not set),desktop,Chrome,Windows,Netherlands,2,2,4,<NA>,<NA>,1,<NA>
99998,879922859128881914,1496326927,2017-06-01,Organic Search,google,organic,(not set),desktop,Chrome,Windows,Czechia,2,2,11,<NA>,<NA>,1,<NA>
99999,3260320371796746614,1496334861,2017-06-01,Organic Search,google,organic,(not set),desktop,Chrome,Macintosh,Australia,2,2,12,<NA>,<NA>,1,<NA>

In [21]:
df.head()

,fullVisitorId,visitId,visit_date,channelGrouping,source,medium,campaign,deviceCategory,browser,operatingSystem,country,pageviews,hits,timeOnSite,transactions,transactionRevenue,newVisits,bounces
0,4598890394865817235,1486932897,2017-02-12,Direct,(direct),(none),(not set),mobile,Android Webview,Android,Netherlands,1,1,<NA>,<NA>,<NA>,1,1
1,085297959192196865,1486906252,2017-02-12,Organic Search,google,organic,(not set),mobile,Chrome,Android,United Kingdom,1,1,<NA>,<NA>,<NA>,<NA>,1
2,2211677311320024670,1486956669,2017-02-12,Direct,(direct),(none),(not set),mobile,Chrome,Android,Argentina,1,1,<NA>,<NA>,<NA>,<NA>,1
3,8969779493563769417,1486922640,2017-02-12,Organic Search,google,organic,(not set),mobile,Safari,iOS,United States,1,1,<NA>,<NA>,<NA>,<NA>,1
4,9271977665405126573,1486922683,2017-02-12,Organic Search,google,organic,(not set),desktop,Safari,Macintosh,United States,1,1,<NA>,<NA>,<NA>,<NA>,1

In [22]:
df.shape

(100000, 18)

In [10]:
df.columns

Index(['source', 'sessions'], dtype='str')

In [34]:
df.dtypes

fullVisitorId                    str
visitId                        Int64
visit_date            datetime64[us]
channelGrouping                  str
source                           str
medium                           str
campaign                         str
deviceCategory                   str
browser                          str
operatingSystem                  str
country                          str
pageviews                      Int64
hits                           Int64
timeOnSite                     Int64
transactions                   Int64
transactionRevenue             Int64
newVisits                      Int64
bounces                        Int64
dtype: object

In [35]:
# Convert BigQuery dbdate to standard pandas datetime
df["visit_date"] = pd.to_datetime(df["visit_date"].astype(str))

# Verify
print(df.dtypes)

fullVisitorId                    str
visitId                        Int64
visit_date            datetime64[us]
channelGrouping                  str
source                           str
medium                           str
campaign                         str
deviceCategory                   str
browser                          str
operatingSystem                  str
country                          str
pageviews                      Int64
hits                           Int64
timeOnSite                     Int64
transactions                   Int64
transactionRevenue             Int64
newVisits                      Int64
bounces                        Int64
dtype: object

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   fullVisitorId       100000 non-null  str
 1   visitId             100000 non-null  Int64
 2   visit_date          100000 non-null  datetime64[us]
 3   channelGrouping     100000 non-null  str
 4   source              100000 non-null  str
 5   medium              100000 non-null  str
 6   campaign            100000 non-null  str
 7   deviceCategory      100000 non-null  str
 8   browser             100000 non-null  str
 9   operatingSystem     100000 non-null  str
 10  country             100000 non-null  str
 11  pageviews           99987 non-null   Int64
 12  hits                100000 non-null  Int64
 13  timeOnSite          48192 non-null   Int64
 14  transactions        1245 non-null    Int64
 15  transactionRevenue  1237 non-null    Int64
 16  newVisits           78800 non-null   Int64
 17  bounces             51687 non-null   Int64
dtypes: Int64(8), datetime64[us](1), str(9)
memory usage: 22.4 MB

In [43]:
test_df = pd.read_parquet("../data/master_dataset.parquet")

print(test_df.head())

print(test_df.dtypes)

         fullVisitorId     visitId visit_date channelGrouping    source  \
0  4598890394865817235  1486932897 2017-02-12          Direct  (direct)
1   085297959192196865  1486906252 2017-02-12  Organic Search    google
2  2211677311320024670  1486956669 2017-02-12          Direct  (direct)
3  8969779493563769417  1486922640 2017-02-12  Organic Search    google
4  9271977665405126573  1486922683 2017-02-12  Organic Search    google

    medium   campaign deviceCategory          browser operatingSystem  \
0   (none)  (not set)         mobile  Android Webview         Android
1  organic  (not set)         mobile           Chrome         Android
2   (none)  (not set)         mobile           Chrome         Android
3  organic  (not set)         mobile           Safari             iOS
4  organic  (not set)        desktop           Safari       Macintosh

          country  pageviews  hits  timeOnSite  transactions  \
0     Netherlands          1     1        <NA>          <NA>
1  United Kingdom          1     1        <NA>          <NA>
2       Argentina          1     1        <NA>          <NA>
3   United States          1     1        <NA>          <NA>
4   United States          1     1        <NA>          <NA>

   transactionRevenue  newVisits  bounces
0                <NA>          1        1
1                <NA>       <NA>        1
2                <NA>       <NA>        1
3                <NA>       <NA>        1
4                <NA>       <NA>        1
fullVisitorId                    str
visitId                        Int64
visit_date            datetime64[us]
channelGrouping                  str
source                           str
medium                           str
campaign                         str
deviceCategory                   str
browser                          str
operatingSystem                  str
country                          str
pageviews                      Int64
hits                           Int64
timeOnSite                     Int64
transactions                   Int64
transactionRevenue             Int64
newVisits                      Int64
bounces                        Int64
dtype: object

In [37]:
df.isnull().sum()

fullVisitorId             0
visitId                   0
visit_date                0
channelGrouping           0
source                    0
medium                    0
campaign                  0
deviceCategory            0
browser                   0
operatingSystem           0
country                   0
pageviews                13
hits                      0
timeOnSite            51808
transactions          98755
transactionRevenue    98763
newVisits             21200
bounces               48313
dtype: int64

In [38]:
df.describe()

,visitId,visit_date,pageviews,hits,timeOnSite,transactions,transactionRevenue,newVisits,bounces
count,100000.0,100000,99987.0,100000.0,48192.0,1245.0,1237.0,78800.0,51687.0
mean,1485648664.4122,2017-01-28 05:17:08.736000,3.726874,4.45573,268.0791,1.061847,146797687.954729,1.0,1.0
min,1470723616.0,2016-08-09 00:00:00,1.0,1.0,1.0,1.0,1470000.0,1.0,1.0
25%,1477318371.5,2016-10-24 00:00:00,1.0,1.0,35.0,1.0,24680000.0,1.0,1.0
50%,1486926202.5,2017-02-12 00:00:00,1.0,1.0,87.0,1.0,51140000.0,1.0,1.0
75%,1494745033.5,2017-05-13 00:00:00,3.0,4.0,267.0,1.0,119270000.0,1.0,1.0
max,1501311589.0,2017-07-28 00:00:00,469.0,500.0,14279.0,15.0,8248800000.0,1.0,1.0
std,9535051.261611,NaN,6.926994,9.431892,489.857663,0.507372,447523975.25964,0.0,0.0

In [39]:
df.describe(include="all")

,fullVisitorId,visitId,visit_date,channelGrouping,source,medium,campaign,deviceCategory,browser,operatingSystem,country,pageviews,hits,timeOnSite,transactions,transactionRevenue,newVisits,bounces
count,100000,100000.0,100000,100000,100000,100000,100000,100000,100000,100000,100000,99987.0,100000.0,48192.0,1245.0,1237.0,78800.0,51687.0
unique,89989,<NA>,NaN,8,143,7,6,3,29,16,191,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
top,1957458976293878100,<NA>,NaN,Organic Search,(direct),(none),(not set),desktop,Chrome,Windows,United States,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
freq,32,<NA>,NaN,42337,37669,37669,96798,74109,68526,39310,39511,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
mean,NaN,1485648664.4122,2017-01-28 05:17:08.736000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.726874,4.45573,268.0791,1.061847,146797687.954729,1.0,1.0
min,NaN,1470723616.0,2016-08-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1470000.0,1.0,1.0
25%,NaN,1477318371.5,2016-10-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,35.0,1.0,24680000.0,1.0,1.0
50%,NaN,1486926202.5,2017-02-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,87.0,1.0,51140000.0,1.0,1.0
75%,NaN,1494745033.5,2017-05-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,4.0,267.0,1.0,119270000.0,1.0,1.0
max,NaN,1501311589.0,2017-07-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,469.0,500.0,14279.0,15.0,8248800000.0,1.0,1.0
std,NaN,9535051.261611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.926994,9.431892,489.857663,0.507372,447523975.25964,0.0,0.0

In [41]:
df.to_parquet(
    "../data/master_dataset.parquet",
    index=False
)

print("✅ Master dataset saved successfully!")

✅ Master dataset saved successfully!

# Key Findings

## Dataset Overview

- Successfully loaded 100,000 Google Analytics sessions from BigQuery.
- Verified the schema and data types.
- Revenue and transaction fields are populated only for purchasing sessions.
- The dataset contains expected missing values for behavioral metrics.
- Revenue and engagement metrics are highly skewed, suggesting the presence of high-value users.

## Conclusion

The dataset has been successfully validated and is suitable for exploratory data analysis, feature engineering, and machine learning.