# AdInsight AI

## Notebook 01 – Data Understanding

### Objective

This notebook connects to Google BigQuery, loads the Google Analytics Sample Dataset into Python, and performs the initial exploratory data analysis.

### Technologies

- Google BigQuery
- Python
- Pandas
- Matplotlib
- Plotly

### Dataset

Google Analytics Sample Dataset

Project:
adinsight-ai-504406

In [1]:
# =====================================================
# Import Libraries
# =====================================================

from google.cloud import bigquery
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
# =====================================================
# Create BigQuery Client
# =====================================================

client = bigquery.Client(
    project="adinsight-ai-504406"
)

print("Connected to BigQuery!")

Connected to BigQuery!

In [3]:
# =====================================================
# SQL Query
# =====================================================

query = """
SELECT

    trafficSource.source,

    COUNT(*) AS sessions

FROM
    `bigquery-public-data.google_analytics_sample.ga_sessions_*`

GROUP BY
    trafficSource.source

ORDER BY
    sessions DESC

LIMIT 10
"""

In [4]:
pip show db-dtypes

Name: db-dtypes
Version: 1.7.1
Summary: Pandas Data Types for SQL systems (BigQuery, Spanner)
Home-page: https://github.com/googleapis/google-cloud-python/tree/main/packages/db-dtypes
Author: The db-dtypes Authors
Author-email: googleapis-packages@google.com
License:
Location: d:\Ankita\Github projects\AdInsight-AI\.venv\Lib\site-packages
Requires: numpy, packaging, pandas, pyarrow
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [5]:
import db_dtypes

print("db-dtypes installed successfully!")

db-dtypes installed successfully!

In [6]:
# =====================================================
# Execute Query
# =====================================================

df = client.query(query).to_dataframe()

df

d:\Ankita\Github projects\AdInsight-AI\.venv\Lib\site-packages\google\cloud\bigquery\table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

                 source  sessions
0              (direct)    371469
1                google    241280
2           youtube.com    212602
3              Partners     16411
4  analytics.google.com     16172
5                   dfa      5686
6            google.com      4669
7        m.facebook.com      3365
8                 baidu      3356
9      sites.google.com      2983

In [8]:
df.head()

                 source  sessions
0              (direct)    371469
1                google    241280
2           youtube.com    212602
3              Partners     16411
4  analytics.google.com     16172

In [9]:
df.shape

(10, 2)

In [10]:
df.columns

Index(['source', 'sessions'], dtype='str')

In [11]:
df.dtypes

source        str
sessions    Int64
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   source    10 non-null     str
 1   sessions  10 non-null     Int64
dtypes: Int64(1), str(1)
memory usage: 403.0 bytes

In [14]:
df.describe(include="all")

          source       sessions
count         10           10.0
unique        10           <NA>
top     (direct)           <NA>
freq           1           <NA>
mean         NaN        87799.3
std          NaN  135373.624902
min          NaN         2983.0
25%          NaN         3691.0
50%          NaN        10929.0
75%          NaN      163554.25
max          NaN       371469.0

In [15]:
df.isnull().sum()

source      0
sessions    0
dtype: int64

In [16]:
fig = px.bar(
    df,
    x="source",
    y="sessions",
    title="Top Traffic Sources"
)

fig.show()

# Key Observations

- Successfully connected to Google BigQuery.
- Successfully retrieved data into a Pandas DataFrame.
- Verified the schema and data types.
- Created the first visualization.
- Environment is ready for Exploratory Data Analysis (EDA).